name: livingalonecare_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0 
  firebase_storage: ^13.0.4
  cloud_functions: ^6.0.4
  url_launcher: ^6.3.2
  firebase_messaging: ^16.0.4
  timeago: ^3.6.1

  intl: ^0.20.2
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.1"

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon" # Android 아이콘 이름
  ios: true              
  image_path: "assets/images/fork_logo.png"

flutter_native_splash:
  color: "#FFFFFF" # 스플래시 화면 배경색 (흰색)
  image: "assets/images/fork_logo.png"
  # dark: true # 다크 모드 지원 시
  # android: true
  # ios: true